blockdaemon_api_key: your-api-key
currencies: eur,usd
coins:
  nimiq-2:
    enabled: true
    display_name: Nimiq
    wallets:
      - NQxxxxxx
  
  solana:
    enabled: true
  
  bitcoin:
    enabled: true
    wallets:
      - bc1xxxxxxxxxxxx
  tezos:
    enabled: true
  
  ethereum:  
     enabled: true  
     