port: 8000
blockdaemon_api_key: your-api-key
currencies: eur,usd
coins:
  nimiq-2:
    enabled: false
    display_name: Nimiq
    wallets:
      - NQxxxxxx
  
  solana:
    enabled: true
  
  bitcoin:
    enabled: false
    wallets:
      - bc1xxxxxxxxxxxx
  tezos:
    enabled: true
  
  ethereum:  
     enabled: true  
pushgateway:
  enabled: false
  address: localhost:9191
  job: 'crypto-exporter'
  interval: 60